require: rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'

Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/IndentationWidth:
  Width: 2

Style/Semicolon:
  Enabled: true

Metrics/LineLength:
  Max: 100

Style/EmptyLineBetweenDefs:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false
